export const sampleFormList = [
  {
    name: 'Prescription Form A',
    previewData:
      'eyJmb3JtX3N0cnVjdHVyZSI6W3siY3NzQ2xhc3MiOiJzdGF0aWNUZXh0IiwicmVxdWlyZWQiOiJmYWxzZSIsInNlYXJjaGFibGUiOiJmYWxzZSIsInZhbHVlcyI6IjxwIHN0eWxlPVwidGV4dC1hbGlnbjogY2VudGVyO1wiPjxzdHJvbmc+UHJpdmF0ZSBQcmVzY3JpcHRpb248XC9zdHJvbmc+PFwvcD5cbjxwIHN0eWxlPVwidGV4dC1hbGlnbjogY2VudGVyO1wiPjxzdHJvbmc+W0ZOQU1FXSBbTE5BTUVdIFtET0JdPFwvc3Ryb25nPjxcL3A+XG48cCBzdHlsZT1cInRleHQtYWxpZ246IGNlbnRlcjtcIj48c3Ryb25nPltDTElFTlRTVFJFRVRdIC0mbmJzcDtbQ0xJRU5UQUREUkVTUzJdIC0mbmJzcDtbQ0xJRU5UQ0lUWV0gLSZuYnNwO1tDTElFTlRQT1NUQUxdPFwvc3Ryb25nPjxcL3A+XG48cCBzdHlsZT1cInRleHQtYWxpZ246IGNlbnRlcjtcIj48c3Ryb25nPkFsbGVyZ2llczogW0NVU1RPTS5BbGxlcmdpZXNdPFwvc3Ryb25nPjxcL3A+IiwiZGVmYXVsdHMiOiJ0cnVlIn0seyJjc3NDbGFzcyI6ImNsX2RydWdzIiwicmVxdWlyZWQiOiJmYWxzZSIsInNlYXJjaGFibGUiOiJmYWxzZSIsInZhbHVlcyI6IjQwNjU0LDc2NjQ5LDkzODAzLDkzODA0LDkzODA1LDk3NDY2In0seyJjc3NDbGFzcyI6ImlucHV0X3RleHQiLCJyZXF1aXJlZCI6InRydWUiLCJzZWFyY2hhYmxlIjoiZmFsc2UiLCJ2YWx1ZXMiOiJEYXRlIEFkbWluaXN0cmF0aW9uIiwiZGVmYXVsdHMiOiIiLCJsaW5rZWQiOiIwIiwiZmxkdHlwZSI6InRleHQiLCJmbGR3aWR0aCI6ImNvbC1tZC0xMiIsInRyaWdnZXIiOiJudWxsIn0seyJjc3NDbGFzcyI6ImlucHV0X3RleHQiLCJyZXF1aXJlZCI6InRydWUiLCJzZWFyY2hhYmxlIjoiZmFsc2UiLCJ2YWx1ZXMiOiJBZG1pbmlzdGVyZWQgYnkiLCJkZWZhdWx0cyI6IiIsImxpbmtlZCI6IjAiLCJmbGR0eXBlIjoidGV4dCIsImZsZHdpZHRoIjoiY29sLW1kLTEyIiwidHJpZ2dlciI6Im51bGwifSx7ImNzc0NsYXNzIjoic2lnbmF0dXJlIiwicmVxdWlyZWQiOiJmYWxzZSIsInNlYXJjaGFibGUiOiJmYWxzZSIsInRpdGxlIjoiUHJlc2NyaWJlciBTaWduYXR1cmUifV19',
    favorite: false,
  },
  {
    name: 'Prescription Form B',
    previewData:
      'eyJmb3JtX3N0cnVjdHVyZSI6W3siY3NzQ2xhc3MiOiJoZWFkaW5nIiwicmVxdWlyZWQiOiJmYWxzZSIsImRlZmF1bHRzIjoiIiwiZmxkdHlwZSI6IiIsImxpbmtlZCI6IiIsInRpdGxlIjoiIiwidmFsdWVzIjoidGhpcyBpcyBhbiBleGFtcGxlIn0seyJjc3NDbGFzcyI6InJhZGlvIiwicmVxdWlyZWQiOiJmYWxzZSIsImRlZmF1bHRzIjoiIiwiZmxkdHlwZSI6IiIsImxpbmtlZCI6IiIsInRpdGxlIjoiIiwidmFsdWVzIjoiIn1dfQ==',
    favorite: false,
  },
  {
    name: 'Prescription Form C',
    previewData:
      'eyJmb3JtX3N0cnVjdHVyZSI6W3siY3NzQ2xhc3MiOiJzdGF0aWNUZXh0IiwicmVxdWlyZWQiOiJmYWxzZSIsInNlYXJjaGFibGUiOiJmYWxzZSIsInZhbHVlcyI6IjxwIHN0eWxlPVwidGV4dC1hbGlnbjogY2VudGVyO1wiPjxzdHJvbmc+UHJpdmF0ZSBQcmVzY3JpcHRpb248XC9zdHJvbmc+PFwvcD5cbjxwIHN0eWxlPVwidGV4dC1hbGlnbjogY2VudGVyO1wiPjxzdHJvbmc+W0ZOQU1FXSBbTE5BTUVdIFtET0JdPFwvc3Ryb25nPjxcL3A+XG48cCBzdHlsZT1cInRleHQtYWxpZ246IGNlbnRlcjtcIj48c3Ryb25nPltDTElFTlRTVFJFRVRdIC0mbmJzcDtbQ0xJRU5UQUREUkVTUzJdIC0mbmJzcDtbQ0xJRU5UQ0lUWV0gLSZuYnNwO1tDTElFTlRQT1NUQUxdPFwvc3Ryb25nPjxcL3A+XG48cCBzdHlsZT1cInRleHQtYWxpZ246IGNlbnRlcjtcIj48c3Ryb25nPkFsbGVyZ2llczogW0NVU1RPTS5BbGxlcmdpZXNdPFwvc3Ryb25nPjxcL3A+IiwiZGVmYXVsdHMiOiJ0cnVlIn0seyJjc3NDbGFzcyI6ImNsX2RydWdzIiwicmVxdWlyZWQiOiJmYWxzZSIsInNlYXJjaGFibGUiOiJmYWxzZSIsInZhbHVlcyI6IjQwNjU0LDc2NjQ5LDkzODAzLDkzODA0LDkzODA1LDk3NDY2In0seyJjc3NDbGFzcyI6ImlucHV0X3RleHQiLCJyZXF1aXJlZCI6InRydWUiLCJzZWFyY2hhYmxlIjoiZmFsc2UiLCJ2YWx1ZXMiOiJEYXRlIEFkbWluaXN0cmF0aW9uIiwiZGVmYXVsdHMiOiIiLCJsaW5rZWQiOiIwIiwiZmxkdHlwZSI6InRleHQiLCJmbGR3aWR0aCI6ImNvbC1tZC0xMiIsInRyaWdnZXIiOiJudWxsIn0seyJjc3NDbGFzcyI6ImlucHV0X3RleHQiLCJyZXF1aXJlZCI6InRydWUiLCJzZWFyY2hhYmxlIjoiZmFsc2UiLCJ2YWx1ZXMiOiJBZG1pbmlzdGVyZWQgYnkiLCJkZWZhdWx0cyI6IiIsImxpbmtlZCI6IjAiLCJmbGR0eXBlIjoidGV4dCIsImZsZHdpZHRoIjoiY29sLW1kLTEyIiwidHJpZ2dlciI6Im51bGwifSx7ImNzc0NsYXNzIjoic2lnbmF0dXJlIiwicmVxdWlyZWQiOiJmYWxzZSIsInNlYXJjaGFibGUiOiJmYWxzZSIsInRpdGxlIjoiUHJlc2NyaWJlciBTaWduYXR1cmUifV19',
    favorite: false,
  },
  {
    name: 'Prescription Form D',
    previewData:
      'eyJmb3JtX3N0cnVjdHVyZSI6W3siY3NzQ2xhc3MiOiJoZWFkaW5nIiwicmVxdWlyZWQiOiJmYWxzZSIsImRlZmF1bHRzIjoiIiwiZmxkdHlwZSI6IiIsImxpbmtlZCI6IiIsInRpdGxlIjoiIiwidmFsdWVzIjoidGhpcyBpcyBhbiBleGFtcGxlIn0seyJjc3NDbGFzcyI6InJhZGlvIiwicmVxdWlyZWQiOiJmYWxzZSIsImRlZmF1bHRzIjoiIiwiZmxkdHlwZSI6IiIsImxpbmtlZCI6IiIsInRpdGxlIjoiIiwidmFsdWVzIjoiIn1dfQ==',
    favorite: false,
  },
  {
    name: 'Prescription Form E',
    previewData:
      'eyJmb3JtX3N0cnVjdHVyZSI6W3siY3NzQ2xhc3MiOiJzdGF0aWNUZXh0IiwicmVxdWlyZWQiOiJmYWxzZSIsInNlYXJjaGFibGUiOiJmYWxzZSIsInZhbHVlcyI6IjxwIHN0eWxlPVwidGV4dC1hbGlnbjogY2VudGVyO1wiPjxzdHJvbmc+UHJpdmF0ZSBQcmVzY3JpcHRpb248XC9zdHJvbmc+PFwvcD5cbjxwIHN0eWxlPVwidGV4dC1hbGlnbjogY2VudGVyO1wiPjxzdHJvbmc+W0ZOQU1FXSBbTE5BTUVdIFtET0JdPFwvc3Ryb25nPjxcL3A+XG48cCBzdHlsZT1cInRleHQtYWxpZ246IGNlbnRlcjtcIj48c3Ryb25nPltDTElFTlRTVFJFRVRdIC0mbmJzcDtbQ0xJRU5UQUREUkVTUzJdIC0mbmJzcDtbQ0xJRU5UQ0lUWV0gLSZuYnNwO1tDTElFTlRQT1NUQUxdPFwvc3Ryb25nPjxcL3A+XG48cCBzdHlsZT1cInRleHQtYWxpZ246IGNlbnRlcjtcIj48c3Ryb25nPkFsbGVyZ2llczogW0NVU1RPTS5BbGxlcmdpZXNdPFwvc3Ryb25nPjxcL3A+IiwiZGVmYXVsdHMiOiJ0cnVlIn0seyJjc3NDbGFzcyI6ImNsX2RydWdzIiwicmVxdWlyZWQiOiJmYWxzZSIsInNlYXJjaGFibGUiOiJmYWxzZSIsInZhbHVlcyI6IjQwNjU0LDc2NjQ5LDkzODAzLDkzODA0LDkzODA1LDk3NDY2In0seyJjc3NDbGFzcyI6ImlucHV0X3RleHQiLCJyZXF1aXJlZCI6InRydWUiLCJzZWFyY2hhYmxlIjoiZmFsc2UiLCJ2YWx1ZXMiOiJEYXRlIEFkbWluaXN0cmF0aW9uIiwiZGVmYXVsdHMiOiIiLCJsaW5rZWQiOiIwIiwiZmxkdHlwZSI6InRleHQiLCJmbGR3aWR0aCI6ImNvbC1tZC0xMiIsInRyaWdnZXIiOiJudWxsIn0seyJjc3NDbGFzcyI6ImlucHV0X3RleHQiLCJyZXF1aXJlZCI6InRydWUiLCJzZWFyY2hhYmxlIjoiZmFsc2UiLCJ2YWx1ZXMiOiJBZG1pbmlzdGVyZWQgYnkiLCJkZWZhdWx0cyI6IiIsImxpbmtlZCI6IjAiLCJmbGR0eXBlIjoidGV4dCIsImZsZHdpZHRoIjoiY29sLW1kLTEyIiwidHJpZ2dlciI6Im51bGwifSx7ImNzc0NsYXNzIjoic2lnbmF0dXJlIiwicmVxdWlyZWQiOiJmYWxzZSIsInNlYXJjaGFibGUiOiJmYWxzZSIsInRpdGxlIjoiUHJlc2NyaWJlciBTaWduYXR1cmUifV19',
    favorite: false,
  },
  {
    name: 'Prescription Form F',
    previewData:
      'eyJmb3JtX3N0cnVjdHVyZSI6W3siY3NzQ2xhc3MiOiJoZWFkaW5nIiwicmVxdWlyZWQiOiJmYWxzZSIsImRlZmF1bHRzIjoiIiwiZmxkdHlwZSI6IiIsImxpbmtlZCI6IiIsInRpdGxlIjoiIiwidmFsdWVzIjoidGhpcyBpcyBhbiBleGFtcGxlIn0seyJjc3NDbGFzcyI6InJhZGlvIiwicmVxdWlyZWQiOiJmYWxzZSIsImRlZmF1bHRzIjoiIiwiZmxkdHlwZSI6IiIsImxpbmtlZCI6IiIsInRpdGxlIjoiIiwidmFsdWVzIjoiIn1dfQ==',
    favorite: false,
  },
]
