image: node:alpine

pipelines:
  branches:
    default:
      - step:
          name: Build and Test branch
          caches:
            - node
          script:
            - npm install
            - npm test
    master:
      - step:
          name: Build and release master
          caches:
            - node
          script:
            - npm install
            - npm run build
            - npm run nx deploy
            - apk add gettext
            - envsubst < tools/cicd/deploy.sh > deploy-out.sh
            - pipe: atlassian/ssh-run:0.2.8
              variables:
                SSH_USER: 'root'
                SERVER: 'pods.pabau.com'
                MODE: 'script'
                COMMAND: 'deploy-out.sh'
