image: node:alpine

definitions:
  caches:
    nextcache: .next/cache
  services:
    docker:
      memory: 2048
pipelines:
  branches:
    default:
      - step:
          name: Build and Test branch
          caches:
            - node
          script:
            - yarn ci
            - yarn run nx affected --target=lint --base=master~1 --head=master
#            - yarn run nx affected --target=test --base=master~1 --head=master
            - yarn run nx affected --target=build --base=master~1 --head=master
    master:
#      - step:
#          size: 2x
#          name: Build and release master
#          caches:
#            - node
#            - nextcache
#          services:
#            - docker
#          script:
#            - yarn
#            - yarn run nx build
#            - yarn run nx deploy
      - step:
          name: Build and release web via ssh
          script:
            - apk add gettext
            - envsubst < tools/cicd/web.deploy.sh > deploy-out.sh
            - pipe: atlassian/ssh-run:0.2.8
              variables:
                SSH_USER: 'root'
                SERVER: 'dev-uk.nodes.pabau.com'
                MODE: 'script'
                COMMAND: 'deploy-out.sh'
      - step:
          name: Build and release storybook via ssh
          script:
            - apk add gettext
            - envsubst < tools/cicd/storybook.deploy.sh > deploy-out.sh
            - pipe: atlassian/ssh-run:0.2.8
              variables:
                SSH_USER: 'root'
                SERVER: 'dev-uk.nodes.pabau.com'
                MODE: 'script'
                COMMAND: 'deploy-out.sh'
