image: node:alpine

pipelines:
  branches:
    master:
      - step:
          name: Build and release
          script:
            - apk add gettext
            - envsubst < tools/cicd/deploy.sh > deploy-out.sh
            - pipe: atlassian/ssh-run:0.2.8
              variables:
                SSH_USER: 'root'
                SERVER: 'pods.pabau.com'
                MODE: 'script'
                COMMAND: 'deploy-out.sh'
