image: node:alpine

options:
  max-time: 15 # max time in minutes for each step

definitions:
  caches:
    nextcache: 'dist/**/.next/cache'
    yarncustom: '/usr/local/share/.cache/yarn'
  services:
    docker:
      memory: 2048

pipelines:
  default:
    - step:
        name: Build and Test branch
        caches:
          - node
          - nextcache
          - yarncustom
        script:
          - yarn
          - yarn run nx affected --all --target=lint
#          - yarn run nx affected --all --target=build
#          - yarn run nx affected --target=lint --base=master~1
#          - yarn run nx affected --target=test --base=master~1 --head=master
#          - yarn run nx affected --target=build --base=master~1
  branches:
    master:
      - step:
          size: 2x
          name: New Deploy scripot
          caches:
            - node
            - nextcache
            - yarncustom
          services:
            - docker
          script:
            - apk --update add git
            - yarn install --frozen-lockfile
            - yarn affected:build --base=HEAD~1
            - yarn affected:build --base=HEAD~1 --prod
            - yarn affected:lint --base=HEAD~1
            - yarn affected:lint --base=HEAD~1 --with-deps
            - yarn affected:test --base=HEAD~1  || true
            - yarn affected:e2e --base=HEAD~1  || true
            - yarn affected --target=export --prod
            - yarn deploy

