image: node:alpine

definitions:
  caches:
    nextcache: .next/cache
  services:
    docker:
      memory: 2048
pipelines:
  default:
    - step:
        name: Build and Test branch
        caches:
          - node
        script:
          - yarn
          - yarn run nx affected --all --target=lint
#          - yarn run nx affected --all --target=build
#          - yarn run nx affected --target=lint --base=master~1
#          - yarn run nx affected --target=test --base=master~1 --head=master
#          - yarn run nx affected --target=build --base=master~1
  branches:
    master:
#      - step:
#          size: 2x
#          name: Build and release master
#          caches:
#            - node
#            - nextcache
#          services:
#            - docker
#          script:
#            - yarn
#            - yarn run nx build
#            - yarn run nx deploy
      - step:
          name: web
          deployment: production-web
          script:
            - apk add gettext
            - envsubst < tools/cicd/web.deploy.sh > deploy-out.sh
            - pipe: atlassian/ssh-run:0.2.8
              variables:
                SSH_USER: 'root'
                SERVER: 'dev-uk.nodes.pabau.com'
                MODE: 'script'
                COMMAND: 'deploy-out.sh'
          after-script:
            - if [[ BITBUCKET_EXIT_CODE -gt 0 ]]; then echo "Step passed"; else echo "Step failed"
            - pipe: atlassian/email-notify:0.3.8
              variables:
                USERNAME: 'pabau'
                PASSWORD: $MAILCHIMP_PASSWORD
                FROM: 'nobody@pabau.com'
                TO: 'ops@pabau.com'
                HOST: 'smtp.mandrillapp.com'
                BODY_PLAIN: "Build built!"
      - step:
          name: backend
          deployment: production-backend
          script:
            - apk add gettext
            - envsubst < tools/cicd/backend.deploy.sh > deploy-out.sh
            - pipe: atlassian/ssh-run:0.2.8
              variables:
                SSH_USER: 'root'
                SERVER: 'dev-uk.nodes.pabau.com'
                MODE: 'script'
                COMMAND: 'deploy-out.sh'
          after-script:
            - if [[ BITBUCKET_EXIT_CODE -gt 0 ]]; then echo "Step passed"; else echo "Step failed"
            - pipe: atlassian/email-notify:0.3.8
              variables:
                USERNAME: 'pabau'
                PASSWORD: $MAILCHIMP_PASSWORD
                FROM: 'nobody@pabau.com'
                TO: 'ops@pabau.com'
                HOST: 'smtp.mandrillapp.com'
                BODY_PLAIN: "Build built backend!"
      - step:
          name: storybook
          script:
            - apk add gettext
            - envsubst < tools/cicd/storybook.deploy.sh > deploy-out.sh
            - pipe: atlassian/ssh-run:0.2.8
              variables:
                SSH_USER: 'root'
                SERVER: 'dev-uk.nodes.pabau.com'
                MODE: 'script'
                COMMAND: 'deploy-out.sh'
