image: node:alpine

definitions:
  caches:
    nextcache: .next/cache
pipelines:
  branches:
    default:
      - step:
          name: Build and Test branch
          caches:
            - node
          script:
            - npm install
            - npm test
    master:
      - step:
          size: 2x
          name: Build and release master
          caches:
            - node
            - nextcache
          services:
            - docker
          script:
            - yarn
            - yarn run nx build
            - yarn run nx deploy
      - step:
          name: Build and release master via ssh
          script:
            - apk add gettext
            - envsubst < tools/cicd/storybook.deploy.sh > deploy-out.sh
            - pipe: atlassian/ssh-run:0.2.8
              variables:
                SSH_USER: 'root'
                SERVER: 'pods.pabau.com'
                MODE: 'script'
                COMMAND: 'deploy-out.sh'
