module.exports = {
  frontend: {
    graphql: {
      generator: 'nexus',
      output: 'libs/graphql/crm-mutation',
      disableQueries: true,
      excludeFieldsByModel: {
        User: ['password', 'password_algor', 'salt', 'hash'],
      },
      excludeQueriesAndMutations: ['deleteMany', 'createMany'],
      excludeQueriesAndMutationsByModel: {
        StaffMeta: ['updateMany'],
        UserGroup: ['updateMany'],
        CompanyPermission: ['updateMany'],
        CmContactLocation: ['updateMany'],
        CmContactLabel: ['updateMany'],
        companyMeta: ['upsertOne', 'updateMany'],
        XeroIntegration: ['updateMany'],
        CompanyRoomLocation: ['updateMany'],
        UserGroupMember: ['updateMany'],
        UserPermission: ['updateMany'],
        UserReport: ['updateMany'],
        Company: [
          'findUnique',
          'findMany',
          'createOne',
          'upsertOne',
          'deleteOne',
        ],
        InvProduct: ['createOne', 'updateOne', 'upsertOne', 'updateMany'],
        ServicesMasterCategory: [
          'createOne',
          'updateOne',
          'upsertOne',
          'updateMany',
        ],
        BnfDrug: ['updateOne', 'deleteOne', 'updateMany', 'upsertOne'],
        CompanyMeta: ['upsertOne'],
        CmContact: ['createOne'],
        CmLead: ['createOne'],
        DiscountDisableLocation: ['updateMany'],
        DiscountDisableUser: ['updateMany'],
        DiscountDisableProduct: ['updateMany'],
        DiscountDisableService: ['updateMany'],
        EquipmentLocation: ['updateMany'],
      },
    },
  },
  backend: {
    generator: 'nexus',
    output: 'apps/bridge-api/src/generated/types',
    excludeFieldsByModel: {
      User: ['password', 'password_algor', 'salt', 'hash'],
    },
    excludeQueriesAndMutations: ['deleteMany', 'createMany'],
    excludeQueriesAndMutationsByModel: {
      StaffMeta: ['updateMany'],
      UserGroup: ['updateMany'],
      CompanyPermission: ['updateMany'],
      CmContactLocation: ['updateMany'],
      CmContactLabel: ['updateMany'],
      companyMeta: ['upsertOne', 'updateMany'],
      XeroIntegration: ['updateMany'],
      CompanyRoomLocation: ['updateMany'],
      UserGroupMember: ['updateMany'],
      UserPermission: ['updateMany'],
      UserReport: ['updateMany'],
      Company: [
        'findUnique',
        'findMany',
        'createOne',
        'upsertOne',
        'deleteOne',
      ],
      InvProduct: ['createOne', 'updateOne', 'upsertOne', 'updateMany'],
      ServicesMasterCategory: [
        'createOne',
        'updateOne',
        'upsertOne',
        'updateMany',
      ],
      BnfDrug: ['updateOne', 'deleteOne', 'updateMany', 'upsertOne'],
      CompanyMeta: ['upsertOne'],
      CmContact: ['createOne'],
      CmLead: ['createOne'],
      DiscountDisableLocation: ['updateMany'],
      DiscountDisableUser: ['updateMany'],
      DiscountDisableProduct: ['updateMany'],
      DiscountDisableService: ['updateMany'],
      EquipmentLocation: ['updateMany'],
    },
  },
}
