version: '2'
services:
  production:
    image: registry.pabau.com:5000/monorepo/backend
    stdin_open: true
    tty: true
    labels:
      traefik.frontend.rule: Host:backend.pabau.com
      traefik.port: '3333'
      traefik.enable: 'true'
      io.rancher.container.pull_image: always
