import { AppointmentStatus } from '@pabau/ui'
import moment from 'moment'
import User1 from '../../assets/images/user1.png'
import User2 from '../../assets/images/user2.png'
import User3 from '../../assets/images/user3.png'
import User4 from '../../assets/images/user4.png'
import User5 from '../../assets/images/user5.png'
import User6 from '../../assets/images/user6.png'
import User7 from '../../assets/images/user7.png'
import User8 from '../../assets/images/user8.png'
import User9 from '../../assets/images/user9.png'
import User10 from '../../assets/images/user10.png'

export const clientAppointments = [
  {
    serviceName: 'Botox consultation',
    employee: { name: 'Jemima Mellerio', avatar: User1 },
    status: AppointmentStatus.cancelled,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-06-30T20:15:01Z',
    apptDate: '2022-07-03T20:15:01Z',
    isVirtual: true,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    notes:
      'PCR test conducted on December, 12th, 2021. The results were negative.',
    isVideoCall: 1,
  },
  {
    serviceName: 'Filler consultation',
    employee: { name: 'Jemima Mellerio', avatar: User2 },
    status: AppointmentStatus.noShow,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-07-01T20:15:01Z',
    apptDate: '2021-07-03T20:15:01Z',
    isVirtual: true,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    notes:
      'Procedure performed by doctor Crusher, nurse Ogawa, supervised by doctor Zimmerman.',
    isVideoCall: 1,
  },
  {
    serviceName: 'Dermalux LED Light Therapy',
    employee: { name: 'Jemima Mellerio', avatar: User3 },
    otherEmployees: [{ name: 'Laura Sutton', avatar: User4 }],
    status: AppointmentStatus.noShow,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-07-01T20:15:01Z',
    apptDate: '2021-07-03T20:15:01Z',
    isVirtual: true,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    isVideoCall: 0,
  },
  {
    serviceName: 'Abdominoplasty',
    employee: { name: 'Aydin Austin', avatar: User5 },
    otherEmployees: [
      { name: 'Laura Sutton', avatar: User6 },
      { name: 'Jeff Koons', avatar: User7 },
    ],
    status: AppointmentStatus.noShow,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-07-01T20:15:01Z',
    apptDate: '2021-07-03T20:15:01Z',
    isVirtual: true,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    notes:
      'The equipment was sterilized an hour before the procedure was performed.',
    isVideoCall: 0,
  },
  {
    serviceName: 'Revision Abdominoplasty',
    employee: { name: 'Albert Ward', avatar: User8 },
    status: AppointmentStatus.noShow,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-07-01T20:15:01Z',
    apptDate: '2022-07-03T20:15:01Z',
    isVirtual: true,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    notes:
      'PCR test conducted on December, 12th, 2021. The results were negative.',
    isVideoCall: 1,
  },
  {
    serviceName: 'Brachioplasty',
    employee: { name: 'Hugo Miller', avatar: User9 },
    status: AppointmentStatus.waiting,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-06-30T20:15:01Z',
    apptDate: '2021-08-03T20:15:01Z',
    isVirtual: true,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    isVideoCall: 0,
  },
  {
    serviceName: 'Cellulite - 1 area',
    employee: { name: 'Antonio Gibson', avatar: User10 },
    status: AppointmentStatus.waiting,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-06-30T20:15:01Z',
    apptDate: '2021-08-03T20:15:01Z',
    isVirtual: true,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    isVideoCall: 0,
  },
  {
    serviceName: 'Cellulite - 2 areas',
    employee: { name: 'Joe Campbell', avatar: User1 },
    status: AppointmentStatus.waiting,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-06-30T20:15:01Z',
    apptDate: '2021-08-03T20:15:01Z',
    isVirtual: true,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    isVideoCall: 0,
  },
  {
    serviceName: 'Earlobe repair',
    employee: { name: 'John Wright', avatar: User6 },
    status: AppointmentStatus.waiting,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-06-30T20:15:01Z',
    apptDate: '2021-08-03T20:15:01Z',
    isVirtual: false,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    notes: 'Procedure done with the new laser.',
    isVideoCall: 1,
  },
  {
    serviceName: 'Unilateral ear surgery',
    employee: { name: 'Ted Stevens', avatar: User8 },
    status: AppointmentStatus.waiting,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-06-30T20:15:01Z',
    apptDate: '2021-08-03T20:15:01Z',
    isVirtual: true,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    notes:
      'PCR test conducted on December, 12th, 2021. The results were negative.',
    isVideoCall: 0,
  },
  {
    serviceName: 'Wound care',
    employee: { name: 'Jesse Watson', avatar: User2 },
    status: AppointmentStatus.waiting,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-06-30T20:15:01Z',
    apptDate: '2021-08-03T20:15:01Z',
    isVirtual: true,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    notes:
      'Patient needs to pay for the outstanding amount, by the end of December 2021.',
    isVideoCall: 1,
  },
  {
    serviceName: 'Pre-op assessment',
    employee: { name: 'Ronnie Porter', avatar: User5 },
    status: AppointmentStatus.waiting,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-06-30T20:15:01Z',
    apptDate: '2021-08-03T20:15:01Z',
    isVirtual: false,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    notes: 'Procedure done with the new laser.',
    isVideoCall: 1,
  },
  {
    serviceName: 'Post-op assessment',
    employee: { name: 'Joshua Moore', avatar: User9 },
    status: AppointmentStatus.waiting,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-06-30T20:15:01Z',
    apptDate: '2022-08-03T20:15:01Z',
    isVirtual: false,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    notes:
      'Patient needs to pay for the outstanding amount, by the end of December 2021.',
    isVideoCall: 0,
  },
  {
    serviceName: 'Varicose vein injection',
    employee: { name: 'Isaac Dawson', avatar: User10 },
    status: AppointmentStatus.waiting,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-06-30T20:15:01Z',
    apptDate: '2021-08-03T20:15:01Z',
    isVirtual: true,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    isVideoCall: 0,
  },
  {
    serviceName: 'Surgical tattoo removal',
    employee: { name: 'Myles Thomas', avatar: User4 },
    status: AppointmentStatus.waiting,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: moment().add(-10, 'hours').format(),
    apptDate: '2022-08-25T20:15:01Z',
    isVirtual: true,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    isVideoCall: 1,
  },
  {
    serviceName: 'Virtual Consultation - Acne consultation',
    employee: { name: 'James Berry', avatar: User2 },
    status: AppointmentStatus.waiting,
    locationName: 'The London Skin and Hair Clinic',
    createdDate: '2021-06-30T20:15:01Z',
    apptDate: '2021-08-03T20:15:01Z',
    isVirtual: false,
    smsReminder: true,
    emailReminder: true,
    remindersSent: true,
    notes:
      'Patient needs to pay for the outstanding amount, by the end of December 2021.',
    isVideoCall: 1,
  },
]
