export const initialLeadValues = {
  firstName: '',
  lastName: '',
  Salutation: '',
  DOB: undefined,
  Email: '',
  Description: '',
  MailingStreet: '',
  MailingProvince: '',
  MailingCity: '',
  MailingCountry: '',
  MailingPostal: '',
  Phone: '',
  Mobile: '',
  note: '',
  leadStatus: 0,
  lead_source: undefined,
  location: 0,
  MarketingOptInEmail: false,
  MarketingOptInText: false,
  MarketingOptInPost: false,
  MarketingOptInPhone: false,
}

export const employeeList = [
  { name: 'Jessica Winter', selected: true },
  { name: 'Jeff Hackley', selected: false },
  { name: 'Alexander Wang', selected: false },
  { name: 'Linda Davis', selected: false },
  { name: 'William Tyson', selected: false },
  { name: 'Max Starck', selected: false },
  { name: 'Kyle Walsh', selected: false },
  { name: 'Owen Phillips', selected: false },
  { name: 'Aidan Kelly', selected: false },
  { name: 'Ewan Morgan', selected: false },
  { name: 'Jordan Martin', selected: false },
  { name: 'Grant Dudley', selected: false },
]
