export const clientData = [
  {
    id: 1,
    field_label: 'Salutation',
    field_type: 'Dropdown',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 2,
    field_label: 'Labels',
    field_type: 'Custom',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 3,
    field_label: 'First Name',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 4,
    field_label: 'Last Name',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 5,
    field_label: 'Email',
    field_type: 'Email',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 6,
    field_label: 'Mobile Phone',
    field_type: 'Phone',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 7,
    field_label: 'Phone',
    field_type: 'Phone',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 8,
    field_label: 'Gender',
    field_type: 'Single choice',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 9,
    field_label: 'Marketing Source',
    field_type: 'Dropdown',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 10,
    field_label: 'Referral Name',
    field_type: 'Dropdown',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 11,
    field_label: 'DOB',
    field_type: 'Date',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 12,
    field_label: 'Mailing Street',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 13,
    field_label: 'ID',
    field_type: 'Number',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 14,
    field_label: 'Client ID',
    field_type: 'Number',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 15,
    field_label: 'Created By',
    field_type: 'User',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 16,
    field_label: 'Created Date',
    field_type: 'Date',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 17,
    field_label: 'Preferred Language',
    field_type: 'Dropdown',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
]

export const leadData = [
  {
    id: 31,
    field_label: 'Salutation',
    field_type: 'Dropdown',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 1,
    field_label: 'Labels',
    field_type: 'Custom',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 2,
    field_label: 'First Name',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 3,
    field_label: 'Last Name',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 4,
    field_label: 'Email',
    field_type: 'Email',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 5,
    field_label: 'Mobile Phone',
    field_type: 'Phone',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 6,
    field_label: 'Phone',
    field_type: 'Phone',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 7,
    field_label: 'Gender',
    field_type: 'Single choice',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 8,
    field_label: 'Marketing Source',
    field_type: 'Dropdown',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 9,
    field_label: 'Referral Name',
    field_type: 'Dropdown',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 10,
    field_label: 'DOB',
    field_type: 'Date',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 11,
    field_label: 'Mailing Street',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 12,
    field_label: 'ID',
    field_type: 'number',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 13,
    field_label: 'Lead ID',
    field_type: 'number',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 14,
    field_label: 'Created By',
    field_type: 'User',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 15,
    field_label: 'Created Date',
    field_type: 'Date',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 16,
    field_label: 'Won by',
    field_type: 'User',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 17,
    field_label: 'Won time',
    field_type: 'Date',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 18,
    field_label: 'Lead owner',
    field_type: 'User',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 19,
    field_label: 'Done activities',
    field_type: 'Number',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 20,
    field_label: 'Closed on',
    field_type: 'Date',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 21,
    field_label: 'First activity time',
    field_type: 'Date',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 22,
    field_label: 'Last activity date',
    field_type: 'Date',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 23,
    field_label: 'Last activity (days)',
    field_type: 'Number',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 24,
    field_label: 'Lost reason',
    field_type: 'Dropdown',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 25,
    field_label: 'Total activities',
    field_type: 'Number',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 26,
    field_label: 'Lost time',
    field_type: 'Date',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 27,
    field_label: 'Won by',
    field_type: 'User',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 28,
    field_label: 'Stage',
    field_type: 'Dropdown',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 29,
    field_label: 'Status',
    field_type: 'Dropdown',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
]

export const appointmentData = [
  {
    id: 1,
    field_label: 'Charge',
    field_type: 'Single Choice',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 2,
    field_label: 'Contract',
    field_type: 'Single Choice',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 3,
    field_label: 'Location',
    field_type: 'Dropdown',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 4,
    field_label: 'Service',
    field_type: 'Dropdown',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 5,
    field_label: 'Status',
    field_type: 'Single Choice',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 6,
    field_label: 'Start Date',
    field_type: 'Date',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 7,
    field_label: 'End Date',
    field_type: 'Date',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 8,
    field_label: 'Length',
    field_type: 'Number',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 9,
    field_label: 'All Day',
    field_type: 'Single Choice',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 10,
    field_label: 'With',
    field_type: 'User',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 11,
    field_label: 'Notes',
    field_type: 'Long Text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 12,
    field_label: 'Requested',
    field_type: 'Single Choice',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 13,
    field_label: 'Created Date',
    field_type: 'date',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 14,
    field_label: 'Created By',
    field_type: 'User',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
]

export const productData = [
  {
    id: 1,
    field_label: 'Name',
    field_type: 'paragraph_text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 2,
    field_label: 'Category',
    field_type: 'paragraph_text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 3,
    field_label: 'Barcode',
    field_type: 'paragraph_text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 4,
    field_label: 'SKU',
    field_type: 'paragraph_text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 5,
    field_label: 'Size',
    field_type: 'paragraph_text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 6,
    field_label: 'Supplier Name',
    field_type: 'paragraph_text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 7,
    field_label: 'Description',
    field_type: 'paragraph_text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 8,
    field_label: 'Image',
    field_type: 'upload',
    Category: null,
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 9,
    field_label: 'Cost Price',
    field_type: 'currency',
    Category: null,
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 10,
    field_label: 'Retail Price',
    field_type: 'currency',
    Category: null,
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 11,
    field_label: 'Tax rate',
    field_type: 'dropdown',
    Category: null,
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 12,
    field_label: 'Minimum stock level',
    field_type: 'number',
    Category: null,
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 13,
    field_label: 'Maximum stock level',
    field_type: 'number',
    Category: null,
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 14,
    field_label: 'Stock alerts',
    field_type: 'checkbox',
    Category: null,
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
]

export const staffData = [
  {
    id: 1,
    field_label: 'First name',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 2,
    field_label: 'Last name',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 3,
    field_label: 'Position',
    field_type: 'Dropdown',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 4,
    field_label: 'Birthday',
    field_type: 'Date',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 5,
    field_label: 'Mobile',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 6,
    field_label: 'Email',
    field_type: 'Email',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 7,
    field_label: 'Email',
    field_type: 'Email',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 8,
    field_label: 'Notes',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 9,
    field_label: 'Employment start date',
    field_type: 'Date',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 10,
    field_label: 'Primary location',
    field_type: 'Checkbox',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 11,
    field_label: 'Other locations',
    field_type: 'Checkbox',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 12,
    field_label: 'Services',
    field_type: 'Checkbox',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 13,
    field_label: 'Permissions',
    field_type: 'Checkbox',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
]

export const locationsData = [
  {
    id: 1,
    field_label: 'Location Name',
    field_type: 'Single text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 2,
    field_label: 'Address',
    field_type: 'Short text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 3,
    field_label: 'Address (second line)',
    field_type: 'Short text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 4,
    field_label: 'City',
    field_type: 'Short text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 5,
    field_label: 'Postcode',
    field_type: 'Short text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 6,
    field_label: 'Website',
    field_type: 'Website',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 7,
    field_label: 'Email',
    field_type: 'Short text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 8,
    field_label: 'Phone',
    field_type: 'Number',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 9,
    field_label: 'Assigned Users',
    field_type: 'Multiple Choice',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 10,
    field_label: 'Badges',
    field_type: 'Dropdown',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
]

export const serviceData = [
  {
    id: 1,
    field_label: 'Service name',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 2,
    field_label: 'Service Code',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 3,
    field_label: 'Category',
    field_type: 'Dropdown',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 4,
    field_label: 'Appointment Colour',
    field_type: 'Single Choice',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 5,
    field_label: 'Image',
    field_type: 'Upload',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 6,
    field_label: 'Bundle',
    field_type: 'Dropdown',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 7,
    field_label: 'Auto consumption',
    field_type: 'Single Choice',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 8,
    field_label: 'SKU',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 9,
    field_label: 'Procedure code',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 10,
    field_label: 'Invoice item name',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 11,
    field_label: 'Display text on invoice',
    field_type: 'Single line text',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 12,
    field_label: 'Pricing Type',
    field_type: 'Radio',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 13,
    field_label: 'Service price',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 14,
    field_label: 'Duration',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 23,
    field_label: 'Tax',
    field_type: 'Dropdown',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 15,
    field_label: 'Deposit Type',
    field_type: 'Radio',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 16,
    field_label: 'Employees',
    field_type: 'Multiple Choice',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 17,
    field_label: 'Resources',
    field_type: 'Multiple Choice',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 18,
    field_label: 'Locations',
    field_type: 'Multiple Choice',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 19,
    field_label: 'Friendly name',
    field_type: 'Single line text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 20,
    field_label: 'Description',
    field_type: 'Paragraph Text',
    Category: {
      name: 'Details',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 21,
    field_label: 'Restrict bookings',
    field_type: 'Single Choice',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
  {
    id: 22,
    field_label: 'Service Type',
    field_type: 'Single Choice',
    Category: {
      name: 'System',
    },
    is_required: false,
    is_active: '',
    is_locked: true,
    hidden: false,
  },
]

export const groupData = [
  {
    id: 1,
    name: 'Details',
    no_of_fields: 0,
    is_locked: true,
  },
  {
    id: 2,
    name: 'System',
    no_of_fields: 0,
    is_locked: true,
  },
]
