import { EventsProps } from '@pabau/ui'

export const eventsData: EventsProps[] = [
  {
    id: 1,
    type: 'lostEmail',
    eventName: 'Send brochure Lost Email',
    clientName: 'Kane',
    dateTime: '30-06-2022, 3:15 pm',
    activityChecked: false,
    activityUserName: 'Jeremy Epstein',
  },
  {
    id: 2,
    type: 'call',
    eventName: 'Call to Bruno Ballardin',
    clientName: 'Kane',
    dateTime: '29-06-2022, 3:15 pm',
    activityChecked: false,
    activityUserName: 'Jeremy Epstein',
  },
  {
    id: 3,
    type: 'email',
    eventName: 'Email to Bruno Ballardin',
    clientName: 'Kane',
    dateTime: '28-06-2022, 3:15 pm',
    activityChecked: false,
    activityUserName: 'Jeremy Epstein',
  },
  {
    id: 4,
    type: 'letter',
    eventName: 'Send letter to Bruno Ballardin',
    clientName: 'Kane',
    dateTime: '27-06-2022, 3:15 pm',
    activityChecked: false,
    activityUserName: 'Jeremy Epstein',
  },
  {
    id: 5,
    type: 'sms',
    eventName: 'Send SMS',
    clientName: 'Kane',
    dateTime: '26-06-2022, 3:15 pm',
    activityChecked: false,
    activityUserName: 'Jeremy Epstein',
  },
  {
    id: 6,
    type: 'lostEmail',
    eventName: 'Send brochure Lost Email',
    clientName: 'Kane',
    dateTime: '18-06-2021, 3:15 pm',
    activityChecked: true,
    activityUserName: 'Jeremy Epstein',
  },
  {
    id: 7,
    type: 'sms',
    eventName: 'Send SMS',
    clientName: 'Kane',
    dateTime: '14-05-2021, 3:15 pm',
    activityChecked: true,
    activityUserName: 'Jeremy Epstein',
  },
  {
    id: 8,
    type: 'call',
    eventName: 'Call to Bruno Ballardin',
    clientName: 'Kane',
    dateTime: '14-05-2021, 3:15 pm',
    activityChecked: true,
    activityUserName: 'Jeremy Epstein',
  },
  {
    id: 9,
    type: 'email',
    eventName: 'Email to Bruno Ballardin',
    clientName: 'Kane',
    dateTime: '14-05-2021, 3:15 pm',
    activityChecked: true,
    activityUserName: 'Jeremy Epstein',
  },
  {
    id: 10,
    type: 'letter',
    eventName: 'Send letter to Bruno Ballardin',
    clientName: 'Kane',
    dateTime: '14-05-2021, 3:15 pm',
    activityChecked: true,
    activityUserName: 'Jeremy Epstein',
  },
  {
    id: 11,
    type: 'lostEmail',
    eventName: 'Send brochure Lost Email',
    clientName: 'Kane',
    dateTime: '14-05-2021, 3:15 pm',
    activityChecked: true,
    activityUserName: 'Jeremy Epstein',
  },
]
