import clientImg from '../../assets/images/appointment-client.png'

export const appointmentData = [
  {
    key: '1',
    time: '10:30',
    avatar: clientImg,
    clientName: 'Ralph Edwards',
    serviceName: 'Ablation Skin Blemish - CO2 Laser',
    serviceColor: '#ffadfe',
    checkingStatus: 'Not Checked-in',
    staffMember: 'Dr. Emilly Connor',
    paymentStatus: 'paid',
    status: 'waiting',
    date: '2021-10-21T12:10:28+05:30',
  },
  {
    key: '2',
    time: '10:30',
    avatar: clientImg,
    clientName: 'Sylvia Cole',
    serviceName: 'botox 1 area',
    serviceColor: '#388E3C',
    checkingStatus: 'Not Checked-in',
    staffMember: 'Dr. Emilly Connor',
    paymentStatus: 'paid',
    status: 'waiting',
    date: '2021-10-21T12:10:28+05:30',
  },
  {
    key: '3',
    time: '10:30',
    avatar: clientImg,
    clientName: 'Bessie Cooper',
    serviceName: 'Facial Reconstruction',
    checkingStatus: 'Not Checked-in',
    serviceColor: '#ffadfe',
    staffMember: 'Dr. Emilly Connor',
    paymentStatus: 'unpaid',
    status: 'waiting',
    date: '2021-10-21T12:10:28+05:30',
  },
  {
    key: '4',
    time: '10:30',
    avatar: clientImg,
    clientName: 'Jenny Wilson',
    serviceName: 'Facial Reconstruction',
    checkingStatus: 'Not Checed-in',
    staffMember: 'Dr. Emilly Connor',
    serviceColor: '#acfbb2',
    paymentStatus: 'paid',
    status: 'In Progress',
    date: '2021-10-22T12:10:28+05:30',
  },
  {
    key: '5',
    time: '10:30',
    avatar: clientImg,
    clientName: 'Eleanor Pena',
    serviceName: 'service to test',
    serviceColor: '#acfbb2',
    checkingStatus: 'Not Checed-in',
    staffMember: 'Dr. Emilly Connor',
    paymentStatus: 'unpaid',
    status: 'Arrived',
    date: '2021-10-22T12:10:28+05:30',
  },
  {
    key: '6',
    time: '10:30',
    avatar: clientImg,
    clientName: 'Leslie Alexander',
    serviceName: 'Facial Reconstruction',
    serviceColor: '#388E3C',
    checkingStatus: 'Not Checed-in',
    staffMember: 'Dr. Emilly Connor',
    paymentStatus: 'unpaid',
    status: 'Completed',
    date: '2021-10-22T12:10:28+05:30',
  },
]
