export const initialValues = {
  salutation: '',
  Fname: '',
  Lname: '',
  gender: '',
  MarketingSource: '',
  DOB: undefined,
  preferredLanguage: '',
  Email: '',
  Mobile: '',
  Phone: '',
  MailingProvince: '',
  MailingCountry: '',
  MailingStreet: '',
  MailingCity: '',
  MailingPostal: '',
  OtherStreet: '',
  OtherProvince: '',
  OtherCity: '',
  OtherCountry: '',
  OtherPostal: '',
  MarketingOptInEmail: false,
  MarketingOptInText: false,
  MarketingOptInPost: false,
  MarketingOptInPhone: false,
}
