export const basics = {
  reports: [
    {
      id: 0,
      reportCode: 'NEX01',
      reportName: 'NEX01 - Team Report',
      isNew: true,
      favourite: false,
    },
    {
      id: 1,
      reportCode: 'ST001',
      reportName: 'ST001 - Staff Performance Summary',
      isNew: false,
      favourite: false,
    },

    {
      id: 2,
      reportCode: 'ST002',
      reportName: 'ST002 - Commission Summary',
      isNew: false,
      favourite: false,
    },

    {
      id: 3,
      reportCode: 'ST004',
      reportName: 'ST004 - Staff Performance Tracker',
      isNew: false,
      favourite: false,
    },

    {
      id: 4,
      reportCode: 'ST015',
      reportName: 'ST015 - Staff Hours',
      isNew: false,
      favourite: true,
    },
    {
      id: 5,
      reportCode: 'ST025',
      reportName: 'ST025 - Employee Appointment Summary',
      isNew: false,
      favourite: false,
    },

    {
      id: 6,
      reportCode: 'ST038',
      reportName: 'ST038 - Staff Bookouts',
      isNew: false,
      favourite: false,
    },

    {
      id: 7,
      reportCode: 'ST005',
      reportName: 'ST005 - Employee Holidays To Date',
      isNew: false,
      favourite: false,
    },

    {
      id: 8,
      reportCode: 'ST035',
      reportName: 'ST035 - Staff Days Off',
      isNew: false,
      favourite: false,
    },

    {
      id: 9,
      reportCode: 'ST033',
      reportName: 'ST033 - Daily Employee Stats',
      isNew: false,
      favourite: false,
    },

    {
      id: 10,
      reportCode: 'ST031',
      reportName: 'ST031 - Daily Employee Stats (Summary)',
      isNew: false,
      favourite: false,
    },
    {
      id: 11,
      reportCode: 'ST003',
      reportName: 'ST003 - Commission Report (Retail)',
      isNew: false,
      favourite: false,
    },
    {
      id: 12,
      reportCode: 'ST015',
      reportName: 'ST015 - Staff Hours',
      isNew: false,
      favourite: false,
    },
    {
      id: 13,
      reportCode: 'ST035',
      reportName: 'ST035 - Staff Days Off',
      isNew: false,
      favourite: false,
    },
    {
      id: 14,
      reportCode: 'ST036',
      reportName: 'ST036 - Staff Payroll Report',
      isNew: false,
      favourite: false,
    },
    {
      id: 15,
      reportCode: 'ST037',
      reportName: 'ST037 - Timeslots Report',
      isNew: false,
      favourite: false,
    },
    {
      id: 16,
      reportCode: 'ST0372',
      reportName: 'ST037 - Staff Clock In/Out',
      isNew: false,
      favourite: false,
    },
  ],
  graphData: [
    ['Jan', 20],
    ['Feb', 5],
    ['Mar', 12],
    ['Apr', 20],
    ['May', 5],
    ['Jun', 12],
    ['Jul', 20],
    ['Aug', 5],
    ['Sep', 12],
    ['Oct', 20],
    ['Nov', 5],
    ['Dec', 12],
  ],
}
export const FewReport = {
  catHeading: 'Clients',
  graphDescription: 'New clients by week',
  chartLabel: 'int',
  reports: [
    {
      id: 1,
      reportCode: 'CO001',
      reportName: 'CO001 - Basic Information',
      isNew: false,
      favourite: false,
    },
    {
      id: 2,
      reportCode: 'CO020',
      reportName: 'CO020 - New Clients',
      isNew: false,
      favourite: false,
    },
    {
      id: 3,
      reportCode: 'CO045',
      reportName: 'CO045 - Big Spender by Receipt',
      isNew: false,
      favourite: true,
    },
    {
      id: 4,
      reportCode: 'CO003',
      reportName: 'CO003 - Birthday',
      isNew: false,
      favourite: false,
    },
    {
      id: 5,
      reportCode: 'CO010',
      reportName: 'CO010 - Outstanding Packages',
      isNew: false,
      favourite: true,
    },
    {
      id: 6,
      reportCode: 'CO060',
      reportName: 'CO060 - Duplicate Clients',
      isNew: false,
      favourite: false,
    },
    {
      id: 7,
      reportCode: 'CO035',
      reportName: 'CO035 - Clients by Location',
      isNew: false,
      favourite: true,
    },
    {
      id: 8,
      reportCode: 'CO050',
      reportName: 'CO050 - Client Receipts by Category',
      isNew: false,
      favourite: true,
    },
    {
      id: 9,
      reportCode: 'CO030',
      reportName: 'CO030 - Last Spend',
      isNew: false,
      favourite: true,
    },
    {
      id: 10,
      reportCode: 'CO031',
      reportName: 'CO031 - Last Visit',
      isNew: false,
      favourite: true,
    },
    {
      id: 11,
      reportCode: 'CO046',
      reportName: 'CO046 - First Visit',
      isNew: false,
      favourite: true,
    },
    {
      id: 12,
      reportCode: 'CO105',
      reportName: 'CO105 - Patient Prescriptions',
      isNew: false,
      favourite: true,
    },
    {
      id: 13,
      reportCode: 'CO065',
      reportName: 'CO065 - Client Retail Purchases',
      isNew: false,
      favourite: true,
    },
    {
      id: 14,
      reportCode: 'CO070',
      reportName: 'CO070 - Account Balance',
      isNew: false,
      favourite: true,
    },
    {
      id: 15,
      reportCode: 'CO075',
      reportName: 'CO075 - Client Service Sales',
      isNew: false,
      favourite: true,
    },
    {
      id: 16,
      reportCode: 'CO147',
      reportName: 'CO147 - Medical Data Report',
      isNew: false,
      favourite: true,
    },
    {
      id: 17,
      reportCode: 'CO110',
      reportName: 'CO110 - Clients Treatment Interest',
      isNew: false,
      favourite: true,
    },
    {
      id: 18,
      reportCode: 'CO111',
      reportName: 'CO111 - Never Purchased Before',
      isNew: false,
      favourite: true,
    },
    {
      id: 19,
      reportCode: 'CO115',
      reportName: 'CO115 - Client Enquiry Conversion',
      isNew: false,
      favourite: true,
    },
    {
      id: 20,
      reportCode: 'CO130',
      reportName: 'CO130 - Product Consumption',
      isNew: false,
      favourite: true,
    },
    {
      id: 21,
      reportCode: 'CO135',
      reportName: 'CO135 - Account Activity',
      isNew: false,
      favourite: true,
    },
    {
      id: 22,
      reportCode: 'CO140',
      reportName: 'CO140 - Last Customer Bookings by Employee',
      isNew: false,
      favourite: true,
    },
    {
      id: 23,
      reportCode: 'CO145',
      reportName: 'CO145 - Contact Activity',
      isNew: false,
      favourite: true,
    },
    {
      id: 24,
      reportCode: 'CO146',
      reportName: 'CO146 - Treatment Missing Data',
      isNew: false,
      favourite: true,
    },
    {
      id: 25,
      reportCode: 'CO1452',
      reportName: 'CO145 - Account Balance by Date',
      isNew: false,
      favourite: true,
    },
    {
      id: 26,
      reportCode: 'VA001',
      reportName: 'VA001 - Vaccination Report',
      isNew: false,
      favourite: true,
    },
  ],
  graphData: [
    ['Jan', 20],
    ['Feb', 5],
    ['Mar', 12],
    ['Apr', 20],
    ['May', 5],
    ['Jun', 12],
    ['Jul', 20],
    ['Aug', 5],
    ['Sep', 12],
    ['Oct', 20],
    ['Nov', 5],
    ['Dec', 12],
  ],
}
export const ManyReport = {
  catHeading: 'Sales',
  graphDescription: 'Revenue by week',
  chartLabel: '£',
  reports: [
    {
      id: 1,
      reportCode: 'FI000',
      reportName: 'FI000 - Daily Sales',
      isNew: false,
      favourite: true,
    },
    {
      id: 2,
      reportCode: 'FI001',
      reportName: 'FI001 - Daily Reconciliation',
      isNew: false,
      favourite: false,
    },
    {
      id: 3,
      reportCode: 'FI002',
      reportName: 'FI002 - Daily Payments',
      isNew: false,
      favourite: false,
    },
    {
      id: 4,
      reportCode: 'FI005',
      reportName: 'FI005 - Receipts by Employee - Detailed',
      isNew: false,
      favourite: true,
    },
    {
      id: 5,
      reportCode: 'FI011',
      reportName: 'FI011 - Receipts by Service Category',
      isNew: false,
      favourite: false,
    },
    {
      id: 6,
      reportCode: 'FI010',
      reportName: 'FI010 - Receipts by Retail Category',
      isNew: false,
      favourite: false,
    },
    {
      id: 7,
      reportCode: 'FI022',
      reportName: 'FI022 - Daily Performance Stats',
      isNew: false,
      favourite: true,
    },
    {
      id: 8,
      reportCode: 'FI012',
      reportName: 'FI012 - Receipts by Category',
      isNew: false,
      favourite: false,
    },
    {
      id: 9,
      reportCode: 'FI014',
      reportName: 'FI014 - Sales by Category',
      isNew: false,
      favourite: true,
    },
    {
      id: 10,
      reportCode: 'FI019',
      reportName: 'FI019 - VAT Report',
      isNew: false,
      favourite: false,
    },
    {
      id: 11,
      reportCode: 'FI006',
      reportName: 'FI006 - Sales by Employee Detailed Cross',
      isNew: false,
      favourite: false,
    },
    {
      id: 12,
      reportCode: 'FI015',
      reportName: 'FI015 - Receipts by Employee (Service)',
      isNew: false,
      favourite: true,
    },
    {
      id: 13,
      reportCode: 'FI016',
      reportName: 'FI016 - Receipts by Employee (Retail)',
      isNew: false,
      favourite: false,
    },
    {
      id: 14,
      reportCode: 'FI025',
      reportName: 'FI025 - Receipts by Month',
      isNew: false,
      favourite: false,
    },
    {
      id: 15,
      reportCode: 'FI026',
      reportName: 'FI026 - Monthly Taking (Summary)',
      isNew: false,
      favourite: false,
    },
    {
      id: 16,
      reportCode: 'FI030',
      reportName: 'FI030 - Raised Invoices',
      isNew: false,
      favourite: false,
    },
    {
      id: 17,
      reportCode: 'FI040',
      reportName: 'FI040 - Expenses',
      isNew: false,
      favourite: false,
    },
    {
      id: 18,
      reportCode: 'FI075',
      reportName: 'FI075 - Outstanding Invoices',
      isNew: false,
      favourite: false,
    },
    {
      id: 19,
      reportCode: 'FI085',
      reportName: 'FI085 - Service vs Retail Receipts',
      isNew: false,
      favourite: false,
    },
    {
      id: 20,
      reportCode: 'FI090',
      reportName: 'FI090 - Aged Insurance Debt Report',
      isNew: false,
      favourite: false,
    },
    {
      id: 21,
      reportCode: 'FI017',
      reportName: 'FI017 - Receipts by Employee Detailed (VAT)',
      isNew: false,
      favourite: false,
    },
    {
      id: 22,
      reportCode: 'FI031',
      reportName: 'FI031 - Invoice Activity',
      isNew: false,
      favourite: false,
    },
    {
      id: 23,
      reportCode: 'FI035',
      reportName: 'FI035 - Receipts by Payment Method',
      isNew: false,
      favourite: false,
    },
    {
      id: 24,
      reportCode: 'FI055',
      reportName: 'FI055 - Unpaid Visits',
      isNew: false,
      favourite: false,
    },
    {
      id: 25,
      reportCode: 'FI060',
      reportName: 'FI060 - Free Giveaways',
      isNew: false,
      favourite: false,
    },
    {
      id: 26,
      reportCode: 'FI065',
      reportName: 'FI065 - Appointment Income Projection',
      isNew: false,
      favourite: false,
    },
    {
      id: 27,
      reportCode: 'FI070',
      reportName: 'FI070 - Discount Report',
      isNew: false,
      favourite: false,
    },
    {
      id: 28,
      reportCode: 'FI080',
      reportName: 'FI080 - Sales vs Expense',
      isNew: false,
      favourite: false,
    },
    {
      id: 29,
      reportCode: 'FI155',
      reportName: 'FI155 - Insurance Report',
      isNew: false,
      favourite: false,
    },
    {
      id: 30,
      reportCode: 'OT001',
      reportName: 'OT001 - Sales Conversion',
      isNew: false,
      favourite: false,
    },
    {
      id: 31,
      reportCode: 'OT002',
      reportName: 'OT002 - Telesales Report',
      isNew: false,
      favourite: false,
    },
  ],
  graphData: [
    ['Jan', 20],
    ['Feb', 5],
    ['Mar', 12],
    ['Apr', 20],
    ['May', 5],
    ['Jun', 12],
    ['Jul', 20],
    ['Aug', 5],
    ['Sep', 12],
    ['Oct', 20],
    ['Nov', 5],
    ['Dec', 12],
  ],
}
